"$schema" = 'https://starship.rs/config-schema.json'

palette = 'nord'

add_newline = true

format = """
[richard](underline bold nord10)[ @ ](nord15)[📦](nord14)
($git_branch\n)\
(       $git_status\n)\
$directory[--> ](nord6)"""

[git_branch]
format = "[($branch)(:$remote_branch)]($style)"
style = "bold nord12"

[git_status]
format = "[($all_status)($ahead_behind)]($style)"
style = "bold nord13"
conflicted = "conflicted "
ahead = "${count} ahead "
behind = "${count} behind "
diverged = "${count} ahead ${count} behind "
untracked = "untracked"
stashed = "stashed "
modified = "modified "
staged = "staged "
renamed = "renamed "
deleted = "deleted "
typechanged = "typechanged"

[directory]
style = "bold nord14"

[palettes.nord]
nord0 = '#2e3440'
nord1 = '#3b4252'
nord2 = '#434c5e'
nord3 = '#4c566a'
nord4 = '#d8dee9'
nord5 = '#e5e9f0'
nord6 = '#eceff4'
nord7 = '#8fbcbb'
nord8 = '#88c0d0'
nord9 = '#81a1c1'
nord10 = '#5e81ac'
nord11 = '#bf616a'
nord12 = '#d08770'
nord13 = '#ebcb8b'
nord14 = '#a3be8c'
nord15 = '#b48ead'
